ALTER TABLE student
ADD CONSTRAINT age_checking CHECK ( age>=16 );

ALTER TABLE student
ADD CONSTRAINT name_unique_check UNIQUE (name);

ALTER TABLE student
ALTER COLUMN name SET NOT NULL;

ALTER TABLE student
ALTER COLUMN age SET DEFAULT 20;

